# This file is an optional part of the PanSSH utility.
# It provides service and tooling setup to enable use of PanSSH under Lando.
# See: https://github.com/LastCallMedia/panssh

# Installation:
# Place this file in the same location as your application's .lando.yml file.
# Do one of:
#   Rename it to lando.local.yml, or merge it into your existing .lando.local.yml file.
#   Add .lando.panssh.yml into the postLandoFiles section of your ~/.lando/config.yml
# See: https://docs.lando.dev/landofile/#configuration
#
# Run lando rebuild to apply the changes.

# Commands provided:
#
# lando panssh <site.env> : starts PanSSH for the specified site and environment.
# lando pssh : starts PanSSH for the related site and environment matching your current git branch.

services:
  appserver:
    build_as_root:
      # - echo "Installing panssh..."
      # PanSSH  main script.
      - curl -so /usr/local/bin/panssh https://raw.githubusercontent.com/LastCallMedia/panssh/refs/tags/latest/panssh
      - chmod +x /usr/local/bin/panssh
      # PanSSH readx utility script.
      - mkdir -p /usr/local/lib/panssh/
      - curl -so /usr/local/lib/panssh/readx.source.sh https://raw.githubusercontent.com/LastCallMedia/panssh/refs/tags/latest/readx.source.sh
      # Install Bash tab-completion support.
      - apt-get -qqq update && apt-get -qqq install bash-completion
      # Bash-completion support for the panssh command (and other commands available via `lando ssh`).
      #   For this to work, we would have to either uncomment /etc/bash.bashrc "enable bash completion" section,
      #   or include the equivalent in ~/.bashrc or some other suitable location.
      # - mkdir -p /usr/local/share/bash-completion/completions
      # - curl -so /usr/share/bash-completion/completions/panssh https://raw.githubusercontent.com/LastCallMedia/panssh/refs/tags/latest/bash-completion/panssh
    build:
      # Run terminus (if available) to create the .panssh.sites file.
      - hash terminus && terminus auth:login && terminus site:list --format=csv --fields=name,id > $HOME/.panssh.sites

tooling:
  panssh:
    service: appserver
    description: "Opens an emulated interactive SSH connection to a Pantheon site/environment."
    usage: $0 panssh <site>.<env>
    cmd: panssh
  pssh:
    service: appserver
    description: "Opens an emulated interactive SSH connection to the related site and environment matching your git branch."
    cmd: br="$(git branch --show-current)"; test "$br" = "master" && br="dev"; panssh "$PANTHEON_SITE_NAME.$br"
